# Generated by Django 4.2.1 on 2023-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_blog',
            name='Image',
            field=models.ImageField(upload_to='sai'),
        ),
    ]
