# Generated by Django 4.2.1 on 2023-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_food_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_blog',
            name='id',
        ),
        migrations.AlterField(
            model_name='food_blog',
            name='Tfood',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
